// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Created by Andrey Sidorov.
//	Copyright (C) 2012 Andrey Sidorov.
//
// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//  This source code has been donated to the Public Domain.  Do
//  whatever you want with it.
//
//// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef StringManager_localization
#define StringManager_localization

wchar_t *wlocalization[76][20]=
{
	{L"NEW_GAME",L"NEW GAME",L"NOUVELLE PARTIE",L"NEUES SPIEL",L"NUEVA PARTIDA",L"NUOVA PARTITA",L"ニューゲーム",L"НОВАЯ ИГРА",L"새 게임",L"新游戏",L"NOVA PARTIDA"},
	{L"OPTIONS",L"OPTIONS ",L"OPTIONS",L"OPTIONEN",L"OPCIONES",L"OPZIONI",L"オプション",L"НАСТРОЙКИ",L"옵션",L"选项",L"OPÇÕES"},
	{L"LANGUAGE",L"LANGUAGE ",L"LANGUE",L"SPRACHE",L"IDIOMA",L"LINGUA",L"言語",L"ЯЗЫК",L"언어",L"语言",L"IDIOMA"},
	{L"CREDITS",L"ABOUT",L"À PROPOS",L"INFO",L"ACERCA DE",L"RICONOSCIMENTI",L"クレジット",L"ОБ ИГРЕ",L"회사 소개",L"关于",L"SOBRE"},
	{L"GAME_INFOS",L"INFO",L"INFOS",L"INFO",L"INFO",L"INFO",L"インフォメーション",L"ИНФОРМАЦИЯ",L"정보",L"信息",L"INFORMAÇÕES"},
	{L"ADVANCED_FLIPSCREEN",L"FLIP SCREEN",L"PIVOTER ÉCRAN",L"BILDSCHIRM UMDREHEN",L"GIRAR PANTALLA",L"RUOTA LO SCHERMO",L"フリップ|スクリーン",L"ПЕРЕВОРОТ ЭКРАНА",L"화면 반전",L"反转屏幕",L"INVERTER TELA"},
	{L"SOUNDS_MUSIC",L"MUSIC",L"MUSIQUE",L"MUSIK",L"MÚSICA",L"MUSICA",L"BGM",L"МУЗЫКА",L"음악",L"音乐",L"MÚSICA"},
	{L"SOUNDS_SOUNDFX",L"SOUND FX",L"EFFETS",L"SOUNDEFFEKTE",L"EFECTOS",L"EFFETTI",L"SE",L"ЭФФЕКТЫ",L"효과음",L"音效",L"EFEITOS DE SOM"},
	{L"SOUNDS_VIBRATION",L"VIBRATION",L"VIBRATION",L"VIBRATION",L"VIBRACIÓN",L"VIBRAZIONE",L"振動",L"ВИБРАЦИЯ",L"진동",L"振动",L"VIBRAÇÃO"},
	{L"ON_BOTTON",L"ON",L"OUI",L"AN",L"SÍ",L"SÌ",L"はい",L"ВКЛ",L"켜기",L"开",L"LIG."},
	{L"OFF_BOTTON",L"OFF",L"NON",L"AUS",L"NO",L"NO",L"いいえ",L"ВЫКЛ",L"끄기",L"关",L"DESL."},
	{L"TOUCH_SCREEN_CONTINUE",L"TOUCH THE SCREEN TO CONTINUE",L"TOUCHE L'ÉCRAN POUR CONTINUER",L"BILDSCHIRM BERÜHREN: WEITER",L"TOCA LA PANTALLA PARA CONTINUAR",L"TOCCA LO SCHERMO PER CONTINUARE",L"画面をタップしてください",L"НАЖМИТЕ НА ЭКРАН",L"계속하려면 터치하세요.",L"触摸屏幕继续",L"TOQUE A TELA PARA CONTINUAR"},
	{L"RESUME",L"RESUME",L"REPRENDRE",L"FORTSETZEN",L"REANUDAR",L"RIPRENDI",L"ゲーム再開",L"ПРОДОЛЖИТЬ",L"계속하기",L"回到游戏",L"CONTINUAR"},
	{L"SAVING_CHECKPOINT",L"Saving...",L"Sauvegarde...",L"Speichert...",L"Guardando...",L"Salvataggio...",L"セーブ中……",L"Сохранение…",L"저장하는 중…",L"保存中……",L"Gravando..."},
	{L"MAP_NAME",L"MAP",L"CARTE",L"KARTE",L"MAPA",L"MAPPA",L"マップ",L"КАРТА",L"맵",L"地图",L"MAPA"},
	{L"TIME",L"TIME",L"TEMPS",L"ZEIT",L"TIEMPO",L"TEMPO",L"タイム",L"ВРЕМЯ",L"시간",L"时间",L"TEMPO"},
	{L"SCORE",L"SCORE",L"SCORE",L"ERGEBNIS",L"PUNT.",L"PUNTI",L"スコア",L"СЧЕТ",L"점수",L"得分",L"PONTUAÇÃO"},
	{L"STATS",L"STATS",L"STATS",L"STATISTIK",L"ESTADÍSTICAS",L"STATISTICHE",L"データ",L"СТАТИСТИКА",L"통계",L"总计",L"ESTATÍSTICAS"},
	{L"HOSTCREATE",L"Starting new match...",L"Lancement d'une nouvelle partie...",L"Startet neues Spiel...",L"Comenzando partida nueva...",L"Avvio nuova partita...",L"新しいマッチを|準備中です……",L"Начало новой игры…",L"새 매치를 시작하는 중…",L"开始新比赛……",L"Iniciando uma nova partida..."},
	{L"SETTINGS",L"SETTINGS",L"RÉGLAGES",L"EINSTELLUNGEN",L"AJUSTES",L"IMPOSTAZIONI",L"設定",L"НАСТРОЙКИ",L"설정",L"设置",L"CONFIGURAÇÕES"},
	{L"TIMELIMIT",L"TIME LIMIT (Minutes)",L"LIMITE DE TEMPS (Min.)",L"ZEITLIMIT (Min.)",L"TIEMPO (Min.)",L"TEMPO LIMITE (min.)",L"タイムリミット（分）",L"ВРЕМЯ",L"시간 제한(분)",L"时限（分）",L"LIMITE DE TEMPO (min.)"},
	{L"CLOSE_WINDOW",L"CLOSE",L"FERMER",L"SCHLIESSEN",L"CERRAR",L"CHIUDI",L"中断",L"ЗАКРЫТЬ",L"닫기",L"关闭",L"FECHAR"},
	{L"TO_SELECT",L"TO SELECT ",L"POUR SÉLECTIONNER",L"WÄHLEN",L"PARA ELEGIR",L"PER SCEGLIERE",L"選択",L"ВЫБРАТЬ",L"선택",L"选择",L"PARA SELECIONAR"},
	{L"PAUSED",L"PAUSED ",L"EN PAUSE",L"PAUSE",L"EN PAUSA",L"IN PAUSA",L"ポーズ中",L"ПАУЗА",L"일시 중지",L"暂停",L"PAUSA"},
	{L"RETURN_TO_GAME",L"BACK ",L"RETOUR",L"ZURÜCK",L"ATRÁS",L"INDIETRO",L"戻る",L"НАЗАД",L"뒤로",L"返回",L"VOLTAR"},
	{L"RETURN_TO_MENU",L"MAIN MENU",L"MENU",L"HAUPTMENÜ",L"MENÚ",L"MENU",L"メニュー",L"ГЛАВНОЕ МЕНЮ",L"주 메뉴",L"主菜单",L"MENU"},
	{L"START_LEVEL",L"START MISSION",L"COMMENCER MISSION",L"MISSION STARTEN",L"COMENZAR MISIÓN",L"INIZIA MISSIONE",L"ミッションをスタート",L"НАЧАТЬ УРОВЕНЬ",L"미션 시작",L"开始任务",L"INICIAR MISSÃO"},
	{L"RESTART_LEVEL",L"RESTART MISSION",L"RECOMMENCER MISSION",L"MISSION NEU STARTEN",L"REINICIAR MISIÓN",L"RIAVVIA MISSIONE",L"リスタート",L"НАЧАТЬ ЗАНОВО",L"미션 재시작",L"重新开始任务",L"REINICIAR MISSÃO"},
	{L"RESTART_CHECKPOINT",L"RESTART CHECKPOINT ",L"CHECKPOINT",L"SPEICHERPUNKT LADEN",L"REINICIAR PTO. CONTROL",L"RICARICA CHECKPOINT",L"チェックポイント",L"КОНТР. ТОЧКА",L"체크포인트 재시작",L"重新从存档点开始",L"REINICIAR DO CHECKPOINT"},
	{L"SCORE_STATS",L"SCORE",L"SCORE",L"PUNKTE",L"PUNTOS",L"PUNTEGGIO",L"SCORE",L"СЧЕТ",L"점수",L"分数",L"PONTUAÇÃO"},
	{L"XP_STATS",L"XP",L"XP",L"EP",L"XP",L"PE",L"EXP",L"XP",L"경험치",L"经验值",L"PE"},
	{L"XP_NEEDED_STATS",L"XP NEEDED",L"XP REQUIS",L"EP nötig",L"XP MÁS",L"PE RICHIESTI",L"必要なEXP",L"ОПЫТ",L"xp 필요",L"点经验需求",L"PE necessários"},
	{L"KILLS",L"KILLS",L"FRAGS",L"KILLS",L"BAJAS",L"UCCIS.",L"キル",L"УБИЙСТВ",L"킬",L"击杀",L"MATOU"},
	{L"DEATHS",L"DEATHS",L"MORTS",L"TODE",L"MUERTES",L"MORTI",L"デス",L"СМЕРТИ",L"데스",L"死亡",L"MORREU"},
	{L"CTRL_GYROSCOPIC",L"GYROSCOPE",L"GYROSCOPE",L"GYROSENSOR",L"GIROSCOPIO",L"GIROSCOPIO",L"ジャイロスコープ",L"ГИРОСКОП",L"자이로스코프",L"陀螺仪",L"GIROSCÓPIO"},
	{L"CONFIRM_GYROSCOPIC",L"DO YOU WANT TO PLAY WITH GYROSCOPE?",L"JOUER AVEC LE GYROSCOPE ?",L"GYROSENSOR BENUTZEN?",L"¿USAR LOS CONTROLES GIROSCÓPICOS?",L"VUOI GIOCARE USANDO IL GIROSCOPIO?",L"ジャイロスコープ操作を|オンにしますか？",L"ВКЛЮЧИТЬ ГИРОСКОП?",L"자이로스코프로 플레이하시겠습니까?",L"您想要使用陀螺仪控制模式进行游戏吗？",L"DESEJA JOGAR COM O GIROSCÓPIO?"},
	{L"CTRL_GYRO_AIMING",L"GYROSCOPIC AIMING",L"VISÉE GYRO",L"GYROSENSOR-ZIELEN",L"APUNTAR GIROSCOPIO",L"PUNTAMENTO GIROSCOPIO",L"ジャイロスコープ視点",L"ГИРОСКОП",L"자이로스코프 조준",L"陀螺仪瞄准",L"MIRA GIROSCÓPICA"},
	{L"CTRL_GYRO_QTE",L"GYROSCOPIC QTE",L"QTE GYROSCOPIQUE",L"GYROSENSOR-QTE",L"SECUENCIA GIROSCÓPICA",L"QTE GIROSCOPIO",L"ジャイロスコープ|クイックタイム|イベント",L"QTE ГИРОСКОПОМ ",L"자이로스코프 퀵 이벤트",L"陀螺仪即时反应系统",L"EVENTOS COM GIROSCÓPIO"},
	{L"CTRL_RESET",L"RESET",L"RÉINITIALISER",L"RESET",L"REINICIAR",L"RESETTA",L"リセット",L"СБРОС",L"초기화",L"重置",L"REDEFINIR"},
	{L"CTRL_CANCEL",L"CANCEL",L"ANNULER",L"ABBRECHEN",L"CANCELAR",L"ANNULLA",L"キャンセル",L"ОТМЕНА",L"취소",L"取消 ",L"CANCELAR"},
	{L"CTRL_ACCEPTED",L"ACCEPT",L"ACCEPTER",L"ANNEHMEN",L"ACEPTAR",L"ACCETTA",L"決定",L"ПРИНЯТЬ",L"확인",L"接受",L"ACEITAR"},
	{L"CTRL1_SETTINGS",L"CLASSIC CONTROLS",L"COMMANDES CLASSIQUES",L"KLASSISCHE STEUERUNG",L"CONTROLES CLÁSICOS",L"COMANDI CLASSICI",L"クラシックコントロール",L"КЛАССИЧЕСКОЕ УПРАВЛЕНИЕ",L"클래식",L"经典操作",L"CONTROLE CLÁSSICO"},
	{L"CTRL2_SETTINGS",L"SCREEN TAP",L"COMMANDES TACTILES",L"DIREKT BERÜHREN",L"PANTALLA TÁCTIL",L"TATTILI",L"スクリーンタップ",L"НАЖАТИЕ НА ЭКРАН",L"화면 터치",L"点击屏幕",L"TOQUE NA TELA"},
	{L"CTRL3_SETTINGS",L"VIRTUAL STICKS ",L"STICKS VIRTUELS",L"STEUERELEMENTE",L"JOYSTICKS VIRTUALES",L"PAD VIRTUALI",L"バーチャルスティック",L"ВИРТУАЛЬНЫЕ ДЖОЙСТИКИ",L"가상 스틱",L"虚拟摇杆",L"JOYSTICK VIRTUAL"},
	{L"NUM_MONEY",L"CREDITS GAINED:",L"CRÉDITS REMPORTÉS :",L"CREDITS ERHALTEN:",L"CRÉDITOS CONSEGUIDOS:",L"CREDITI GUADAGNATI:",L"獲得クレジット：",L"ЗАРАБОТАНО ДЕНЕГ:",L"획득한 크레딧:",L"获得点券：",L"CRÉDITOS ADQUIRIDOS:"},
	{L"ACCURACY",L"ACCURACY:",L"PRÉCISION :",L"PRÄZISION:",L"PUNTERÍA:",L"PRECISIONE:",L"命中率：",L"ТОЧНОСТЬ:",L"명중률:",L"命中率：",L"PRECISÃO:"},
	{L"NUM_DOCS",L"DOCUMENTS FOUND:",L"DOCUMENTS TROUVÉS :",L"DOKUMENTE GEFUNDEN:",L"DOC. ENCONTRADOS:",L"DOCUMENTI TROVATI:",L"発見した文書：",L"НАЙДЕНО ДОКУМЕНТОВ:",L"발견한 문서:",L"找到文件：",L"DOCUMENTOS ENCONTRADOS:"},
	{L"LEVEL_DIFFICULTY",L"DIFFICULTY:",L"DIFFICULTÉ :",L"NIVEAU:",L"DIFICULTAD:",L"DIFFICOLTÀ:",L"難易度：",L"СЛОЖНОСТЬ:",L"난이도:",L"难度：",L"DIFICULDADE:"},
	{L"LEVEL_TIME",L"YOUR TIME:",L"TEMPS :",L"ZEIT:",L"TU TIEMPO:",L"TEMPO:",L"クリアタイム：",L"ВАШЕ ВРЕМЯ:",L"현재 기록:",L"本次用时：",L"SEU TEMPO:"},
	{L"BEST_TIME",L"BEST TIME:",L"MEILLEUR TEMPS :",L"BESTZEIT:",L"MEJOR TIEMPO:",L"MIGLIOR TEMPO:",L"ベストタイム：",L"ЛУЧШЕЕ ВРЕМЯ:",L"최고 기록:",L"最短用时：",L"MELHOR TEMPO:"},
	{L"COMPLETED",L"COMPLETED",L"TERMINÉ",L"BEENDET",L"COMPLETADA",L"COMPLETATA",L"COMPLETED",L"ЗАВЕРШЕНО",L"완료",L"完成",L"CONCLUIU"},
	{L"CONFIRM_QUIT",L"ARE YOU SURE THAT YOU WANT TO QUIT?",L"QUITTER ?",L"WILLST DU WIRKLICH DAS SPIEL BEENDEN?",L"¿SEGURO QUE QUIERES SALIR?",L"VUOI DAVVERO USCIRE?",L"終了します\nよろしいですか？",L"ВЫ ТОЧНО ХОТИТЕ ВЫЙТИ?",L"종료하시겠습니까?",L"你确定想要退出吗？",L"TEM CERTEZA DE QUE DESEJA SAIR?"},
	{L"CONFIRM_MAINMENU",L"ARE YOU SURE THAT YOU WANT TO RETURN TO THE MAIN MENU?",L"RETOURNER AU MENU PRINCIPAL ?",L"WILLST DU WIRKLICH ZURÜCK ZUM HAUPTMENÜ?",L"¿SEGURO QUE QUIERES VOLVER AL MENÚ PRINCIPAL?",L"VUOI DAVVERO TORNARE AL MENU PRINCIPALE?",L"メインメニューに戻ります\nよろしいですか？",L"ВЫ ТОЧНО ХОТИТЕ ВЕРНУТЬСЯ В ГЛАВНОЕ МЕНЮ?",L"주 메뉴로 돌아가시겠습니까?",L"你确定想要返回主菜单吗？",L"TEM CERTEZA DE QUE DESEJA VOLTAR AO MENU PRINCIPAL?"},
	{L"CONFIRM_EXITMATCH",L"ARE YOU SURE THAT YOU WANT TO LEAVE THIS MATCH?",L"ES-TU SÛR DE VOULOIR QUITTER CETTE PARTIE ?",L"BIST DU SICHER, DASS DU DAS SPIEL VERLASSEN MÖCHTEST?",L"¿SEGURO QUE QUIERES SALIR DE LA PARTIDA?",L"VUOI DAVVERO LASCIARE QUESTA PARTITA?",L"退出します\nよろしいですか？",L"ПОКИНУТЬ МАТЧ?",L"이 매치에서 나가시겠습니까?",L"你确定要离开比赛吗？",L"VOCÊ TEM CERTEZA QUE DESEJA SAIR DA PARTIDA?"},
	{L"CONFIRM_RESTART",L"ARE YOU SURE THAT YOU WANT TO RESTART THIS MISSION?",L"RECOMMENCER CETTE MISSION ?",L"WILLST DU DIESE MISSION WIRKLICH NEU STARTEN?",L"¿SEGURO QUE QUIERES REINICIAR ESTA MISIÓN?",L"VUOI DAVVERO RICOMINCIARE LA MISSIONE?",L"ミッションをリスタートします\nよろしいですか？",L"ВЫ ТОЧНО ХОТИТЕ НАЧАТЬ ЗАДАНИЕ ЗАНОВО?",L"이 미션을 다시 시작하시겠습니까?",L"你确定想要重新开始本关吗？",L"TEM CERTEZA DE QUE DESEJA REINICIAR A MISSÃO?"},
	{L"CONFIRM_NEWGAME",L"ARE YOU SURE THAT YOU WANT TO START A NEW GAME?",L"COMMENCER UNE NOUVELLE PARTIE ?",L"WILLST DU WIRKLICH EIN NEUES SPIEL STARTEN?",L"¿SEGURO QUE QUIERES EMPEZAR UNA NUEVA PARTIDA?",L"VUOI DAVVERO INIZIARE UNA NUOVA PARTITA?",L"新しくゲームを開始します\n以前のプレイデータは\n失われます",L"ВЫ ТОЧНО ХОТИТЕ НАЧАТЬ ИГРУ ЗАНОВО?",L"게임을 새로 시작하시겠습니까?",L"你确定想要开始一个新的游戏吗？",L"TEM CERTEZA DE QUE DESEJA INICIAR UMA NOVA PARTIDA?"},
	{L"CONFIRM_CHECKPOINT",L"ARE YOU SURE THAT YOU WANT TO RELOAD THE LAST CHECKPOINT?",L"REPRENDRE DU DERNIER CHECKPOINT ?",L"WILLST DU WIRKLICH DEN LETZTEN SPEICHERPUNKT LADEN?",L"¿SEGURO QUE QUIERES EMPEZAR DESDE EL ÚLTIMO PUNTO DE CONTROL?",L"VUOI DAVVERO RIPARTIRE DALL'ULTIMO CHECKPOINT?",L"直前のチェックポイントに|戻ります\nよろしいですか？",L"ВЫ ТОЧНО ХОТИТЕ НАЧАТЬ С ПОСЛЕДНЕЙ КОНТРОЛЬНОЙ ТОЧКИ?",L"마지막 체크포인트를 다시 불러오시겠습니까?",L"你确定要从最近的存档点重新开始吗？",L"TEM CERTEZA DE QUE DESEJA RECARREGAR O ÚLTIMO CHECKPOINT?"},
	{L"CONFIRM_YES",L"YES",L"OUI",L"JA",L"SÍ",L"SÌ",L"はい",L"ДА",L"예",L"是",L"SIM"},
	{L"CONFIRM_NO",L"NO",L"NON",L"NEIN",L"NO",L"NO",L"いいえ",L"НЕТ",L"아니요",L"否",L"NÃO"},
	{L"CONFIRM_REHOST",L"ARE YOU SURE YOU WANT TO END THIS GAME AND START ANOTHER ONE?",L"TERMINER CETTE PARTIE ET EN COMMENCER UNE NOUVELLE ?",L"WILLST DU WIRKLICH DIESES SPIEL BEENDEN UND EIN NEUES STARTEN?",L"¿SEGURO QUE QUIERES SALIR DE ESTA PARTIDA Y EMPEZAR UNA NUEVA?",L"VUOI TERMINARE QUESTA PARTITA E INIZIARNE UNA NUOVA?",L"この対戦を終了して|別の対戦を始めます\nよろしいですか？",L"ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ ЗАВЕРШИТЬ ЭТУ ИГРУ И НАЧАТЬ НОВУЮ?",L"이 게임을 끝내고 다른 게임을 시작하시겠습니까?",L"你确定想要结束此关游戏并重新开始新的游戏吗？",L"TEM CERTEZA DE QUE DESEJA ENCERRAR ESTA PARTIDA E INICIAR OUTRA?"},
	{L"CONFIRM_BACK",L"BACK",L"RETOUR",L"ZURÜCK",L"ATRÁS",L"INDIETRO",L"戻る",L"BACK",L"뒤로",L"返回",L"VOLTAR"},
	{L"CONFIRM_SUICIDE",L"CHOOSING THIS OPTION WILL CAUSE YOU TO DIE. ARE YOU SURE YOU WANT TO CONTINUE?",L"TON PERSONNAGE MOURRA SI TU CHOISIS CETTE OPTION. CONTINUER ?",L"WENN DU DIESE OPTION WÄHLST, STIRBST DU. WIRKLICH FORTFAHREN?",L"SI ELIGES ESTA OPCIÓN, MORIRÁS. ¿SEGURO QUE QUIERES CONTINUAR?",L"SE SCEGLI QUESTA OPZIONE, MORIRAI. VUOI DAVVERO CONTINUARE?",L"デスの|スコアが|+1され|再出撃と|なります\nよろしい|ですか？",L"ВЫБОР ЭТОЙ ФУНКЦИИ ПРИВЕДЕТ К СМЕРТИ ПЕРСОНАЖА. ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ ПРОДОЛЖИТЬ?",L"이 옵션을 선택하면 죽게 됩니다. 계속하시겠습니까?",L"选择此项意味自杀身亡。你确定想要继续？",L"ESTA OPÇÃO RESULTARÁ EM SUA MORTE. TEM CERTEZA DE QUE DESEJA CONTINUAR?"},
	{L"CONFIRM_RESET_SAVEGAME",L"STARTING THIS LEVEL WILL ERASE YOUR PREVIOUS SAVED GAME. CONTINUE?",L"SI TU COMMENCES CE NIVEAU, TA PROGRESSION SERA EFFACÉE. CONTINUER ?",L"WENN DU DIESEN LEVEL STARTEST, GEHT DEIN BISHERIGER FORTSCHRITT VERLOREN. FORTFAHREN?",L"SI EMPIEZAS ESTE NIVEL, SE BORRARÁ TU ANTERIOR PARTIDA GUARDADA. ¿QUIERES CONTINUAR?",L"SE INIZIERAI QUESTO LIVELLO, PERDERAI I SALVATAGGI PRECEDENTI. CONTINUARE?",L"このステージを|開始すると|以前の|ステージの\n途中データが|削除されます\nよろしいですか？",L"ПРЕДЫДУЩИЕ СОХРАНЕНИЯ БУДУТ УДАЛЕНЫ, ЕСЛИ ВЫ НАЧНЕТЕ ЭТОТ УРОВЕНЬ. ПРОДОЛЖИТЬ?",L"이 레벨을 시작하면 이전에 저장된 게임이 삭제됩니다. 계속하시겠습니까?",L"开始本关会清除你之前的储存进度。要继续吗？",L"SE VOCÊ COMEÇAR ESSE NÍVEL VAI APAGAR SEU JOGO SALVO ANTERIORMENTE. DESEJA CONTINUAR?"},
	{L"EASY_DIFFICULTY",L"EASY ",L"FACILE",L"LEICHT",L"BAJA",L"FACILE",L"イージー",L"ЛЕГКО",L"쉬움",L"简单",L"FÁCIL"},
	{L"NORMAL_DIFFICULTY",L"NORMAL ",L"NORMAL",L"NORMAL",L"MEDIA",L"NORMALE",L"ノーマル",L"НОРМАЛЬНО",L"보통",L"普通",L"NORMAL"},
	{L"HARD_DIFFICULTY",L"HARD ",L"DIFFICILE",L"SCHWER",L"ALTA",L"DIFFICILE",L"ハード",L"ТЯЖЕЛО",L"어려움",L"困难",L"DIFÍCIL"},
	{L"EXTREME_DIFFICULTY",L"EXTREME ",L"EXTRÊME",L"EXTREM",L"EXTREMA",L"ESTREMA",L"エクストリーム",L"ЭКСТРИМ",L"아주 어려움",L"噩梦",L"EXTREMO"},
	{L"PRESS",L"TOUCH ",L"TOUCHE",L"BILDSCHIRM BERÜHREN:",L"TOCA",L"TOCCA",L"タップして",L"НАЖМИТЕ",L"계속하려면",L"触摸",L"TOQUE"},
	{L"TO_CONTINUE",L"TO CONTINUE ",L"POUR CONTINUER",L"WEITER",L"PARA CONTINUAR",L"PER CONTINUARE",L"コンティニュー",L"ЧТОБЫ ПРОДОЛЖИТЬ",L"터치하세요",L"以继续",L"PARA CONTINUAR"},
	{L"BACK",L"BACK ",L"RETOUR",L"ZURÜCK",L"ATRÁS",L"INDIETRO",L"戻る",L"НАЗАД",L"뒤로",L"返回",L"VOLTAR"},
	{L"LOADING",L"LOADING",L"CHARGEMENT",L"LÄDT",L"CARGANDO",L"CARICAMENTO",L"LOADING",L"ЗАГРУЗКА",L"불러오는 중",L"载入中",L"CARREGANDO"},
	{L"MAX",L"MAX",L"MAX.",L"MAX.",L"MÁX.",L"MAX",L"MAX",L"МАКС",L"최대",L"最高",L"MÁX."},
	{L"HEALTH",L"Health",L"Santé",L"Gesundheit",L"Salud",L"Energia",L"Health",L"ЗДОРОВЬЕ",L"체력",L"生命值",L"Saúde"},
	{L"YOU",L"YOU",L"TOI",L"DU",L"TÚ",L"TU",L"あなた",L"Вы",L"나",L"你",L"VOCÊ"},
	{L"SUDDEN_DEATH",L"SUDDEN DEATH!",L"MORT SUBITE !",L"PLÖTZLICHER TOD!",L"¡MUERTE SÚBITA!",L"MORTE IMPROVVISA",L"サドンデス",L"НЕОЖИДАННАЯ СМЕРТЬ!!!",L"서든데스!",L"突然死亡！",L"MORTE SÚBITA!"},
	{L"TROPH_TITLE",L"To Be Continued?",L"À suivre ?",L"Fortsetzung folgt?",L"¿Continuará?",L"La storia continua...",L"プロローグ",L"Продолжение следует?",L"전투의 서막",L"继续？",L"Continua...?"}
};

char *localization[76][20]=
{
	{"NEW_GAME","NEW GAME","NOUVELLE PARTIE","NEUES SPIEL","NUEVA PARTIDA","NUOVA PARTITA","ニューゲーム","НОВАЯ ИГРА","새 게임","新游戏","NOVA PARTIDA"},
	{"OPTIONS","OPTIONS ","OPTIONS","OPTIONEN","OPCIONES","OPZIONI","オプション","НАСТРОЙКИ","옵션","选项","OPÇÕES"},
	{"LANGUAGE","LANGUAGE ","LANGUE","SPRACHE","IDIOMA","LINGUA","言語","ЯЗЫК","언어","语言","IDIOMA"},
	{"CREDITS","ABOUT","À PROPOS","INFO","ACERCA DE","RICONOSCIMENTI","クレジット","ОБ ИГРЕ","회사 소개","关于","SOBRE"},
	{"GAME_INFOS","INFO","INFOS","INFO","INFO","INFO","インフォメーション","ИНФОРМАЦИЯ","정보","信息","INFORMAÇÕES"},
	{"ADVANCED_FLIPSCREEN","FLIP SCREEN","PIVOTER ÉCRAN","BILDSCHIRM UMDREHEN","GIRAR PANTALLA","RUOTA LO SCHERMO","フリップ|スクリーン","ПЕРЕВОРОТ ЭКРАНА","화면 반전","反转屏幕","INVERTER TELA"},
	{"SOUNDS_MUSIC","MUSIC","MUSIQUE","MUSIK","MÚSICA","MUSICA","BGM","МУЗЫКА","음악","音乐","MÚSICA"},
	{"SOUNDS_SOUNDFX","SOUND FX","EFFETS","SOUNDEFFEKTE","EFECTOS","EFFETTI","SE","ЭФФЕКТЫ","효과음","音效","EFEITOS DE SOM"},
	{"SOUNDS_VIBRATION","VIBRATION","VIBRATION","VIBRATION","VIBRACIÓN","VIBRAZIONE","振動","ВИБРАЦИЯ","진동","振动","VIBRAÇÃO"},
	{"ON_BOTTON","ON","OUI","AN","SÍ","SÌ","はい","ВКЛ","켜기","开","LIG."},
	{"OFF_BOTTON","OFF","NON","AUS","NO","NO","いいえ","ВЫКЛ","끄기","关","DESL."},
	{"TOUCH_SCREEN_CONTINUE","TOUCH THE SCREEN TO CONTINUE","TOUCHE L'ÉCRAN POUR CONTINUER","BILDSCHIRM BERÜHREN: WEITER","TOCA LA PANTALLA PARA CONTINUAR","TOCCA LO SCHERMO PER CONTINUARE","画面をタップしてください","НАЖМИТЕ НА ЭКРАН","계속하려면 터치하세요.","触摸屏幕继续","TOQUE A TELA PARA CONTINUAR"},
	{"RESUME","RESUME","REPRENDRE","FORTSETZEN","REANUDAR","RIPRENDI","ゲーム再開","ПРОДОЛЖИТЬ","계속하기","回到游戏","CONTINUAR"},
	{"SAVING_CHECKPOINT","Saving...","Sauvegarde...","Speichert...","Guardando...","Salvataggio...","セーブ中……","Сохранение…","저장하는 중…","保存中……","Gravando..."},
	{"MAP_NAME","MAP","CARTE","KARTE","MAPA","MAPPA","マップ","КАРТА","맵","地图","MAPA"},
	{"TIME","TIME","TEMPS","ZEIT","TIEMPO","TEMPO","タイム","ВРЕМЯ","시간","时间","TEMPO"},
	{"SCORE","SCORE","SCORE","ERGEBNIS","PUNT.","PUNTI","スコア","СЧЕТ","점수","得分","PONTUAÇÃO"},
	{"STATS","STATS","STATS","STATISTIK","ESTADÍSTICAS","STATISTICHE","データ","СТАТИСТИКА","통계","总计","ESTATÍSTICAS"},
	{"HOSTCREATE","Starting new match...","Lancement d'une nouvelle partie...","Startet neues Spiel...","Comenzando partida nueva...","Avvio nuova partita...","新しいマッチを|準備中です……","Начало новой игры…","새 매치를 시작하는 중…","开始新比赛……","Iniciando uma nova partida..."},
	{"SETTINGS","SETTINGS","RÉGLAGES","EINSTELLUNGEN","AJUSTES","IMPOSTAZIONI","設定","НАСТРОЙКИ","설정","设置","CONFIGURAÇÕES"},
	{"TIMELIMIT","TIME LIMIT (Minutes)","LIMITE DE TEMPS (Min.)","ZEITLIMIT (Min.)","TIEMPO (Min.)","TEMPO LIMITE (min.)","タイムリミット（分）","ВРЕМЯ","시간 제한(분)","时限（分）","LIMITE DE TEMPO (min.)"},
	{"CLOSE_WINDOW","CLOSE","FERMER","SCHLIESSEN","CERRAR","CHIUDI","中断","ЗАКРЫТЬ","닫기","关闭","FECHAR"},
	{"TO_SELECT","TO SELECT ","POUR SÉLECTIONNER","WÄHLEN","PARA ELEGIR","PER SCEGLIERE","選択","ВЫБРАТЬ","선택","选择","PARA SELECIONAR"},
	{"PAUSED","PAUSED ","EN PAUSE","PAUSE","EN PAUSA","IN PAUSA","ポーズ中","ПАУЗА","일시 중지","暂停","PAUSA"},
	{"RETURN_TO_GAME","BACK ","RETOUR","ZURÜCK","ATRÁS","INDIETRO","戻る","НАЗАД","뒤로","返回","VOLTAR"},
	{"RETURN_TO_MENU","MAIN MENU","MENU","HAUPTMENÜ","MENÚ","MENU","メニュー","ГЛАВНОЕ МЕНЮ","주 메뉴","主菜单","MENU"},
	{"START_LEVEL","START MISSION","COMMENCER MISSION","MISSION STARTEN","COMENZAR MISIÓN","INIZIA MISSIONE","ミッションをスタート","НАЧАТЬ УРОВЕНЬ","미션 시작","开始任务","INICIAR MISSÃO"},
	{"RESTART_LEVEL","RESTART MISSION","RECOMMENCER MISSION","MISSION NEU STARTEN","REINICIAR MISIÓN","RIAVVIA MISSIONE","リスタート","НАЧАТЬ ЗАНОВО","미션 재시작","重新开始任务","REINICIAR MISSÃO"},
	{"RESTART_CHECKPOINT","RESTART CHECKPOINT ","CHECKPOINT","SPEICHERPUNKT LADEN","REINICIAR PTO. CONTROL","RICARICA CHECKPOINT","チェックポイント","КОНТР. ТОЧКА","체크포인트 재시작","重新从存档点开始","REINICIAR DO CHECKPOINT"},
	{"SCORE_STATS","SCORE","SCORE","PUNKTE","PUNTOS","PUNTEGGIO","SCORE","СЧЕТ","점수","分数","PONTUAÇÃO"},
	{"XP_STATS","XP","XP","EP","XP","PE","EXP","XP","경험치","经验值","PE"},
	{"XP_NEEDED_STATS","XP NEEDED","XP REQUIS","EP nötig","XP MÁS","PE RICHIESTI","必要なEXP","ОПЫТ","xp 필요","点经验需求","PE necessários"},
	{"KILLS","KILLS","FRAGS","KILLS","BAJAS","UCCIS.","キル","УБИЙСТВ","킬","击杀","MATOU"},
	{"DEATHS","DEATHS","MORTS","TODE","MUERTES","MORTI","デス","СМЕРТИ","데스","死亡","MORREU"},
	{"CTRL_GYROSCOPIC","GYROSCOPE","GYROSCOPE","GYROSENSOR","GIROSCOPIO","GIROSCOPIO","ジャイロスコープ","ГИРОСКОП","자이로스코프","陀螺仪","GIROSCÓPIO"},
	{"CONFIRM_GYROSCOPIC","DO YOU WANT TO PLAY WITH GYROSCOPE?","JOUER AVEC LE GYROSCOPE ?","GYROSENSOR BENUTZEN?","¿USAR LOS CONTROLES GIROSCÓPICOS?","VUOI GIOCARE USANDO IL GIROSCOPIO?","ジャイロスコープ操作を|オンにしますか？","ВКЛЮЧИТЬ ГИРОСКОП?","자이로스코프로 플레이하시겠습니까?","您想要使用陀螺仪控制模式进行游戏吗？","DESEJA JOGAR COM O GIROSCÓPIO?"},
	{"CTRL_GYRO_AIMING","GYROSCOPIC AIMING","VISÉE GYRO","GYROSENSOR-ZIELEN","APUNTAR GIROSCOPIO","PUNTAMENTO GIROSCOPIO","ジャイロスコープ視点","ГИРОСКОП","자이로스코프 조준","陀螺仪瞄准","MIRA GIROSCÓPICA"},
	{"CTRL_GYRO_QTE","GYROSCOPIC QTE","QTE GYROSCOPIQUE","GYROSENSOR-QTE","SECUENCIA GIROSCÓPICA","QTE GIROSCOPIO","ジャイロスコープ|クイックタイム|イベント","QTE ГИРОСКОПОМ ","자이로스코프 퀵 이벤트","陀螺仪即时反应系统","EVENTOS COM GIROSCÓPIO"},
	{"CTRL_RESET","RESET","RÉINITIALISER","RESET","REINICIAR","RESETTA","リセット","СБРОС","초기화","重置","REDEFINIR"},
	{"CTRL_CANCEL","CANCEL","ANNULER","ABBRECHEN","CANCELAR","ANNULLA","キャンセル","ОТМЕНА","취소","取消 ","CANCELAR"},
	{"CTRL_ACCEPTED","ACCEPT","ACCEPTER","ANNEHMEN","ACEPTAR","ACCETTA","決定","ПРИНЯТЬ","확인","接受","ACEITAR"},
	{"CTRL1_SETTINGS","CLASSIC CONTROLS","COMMANDES CLASSIQUES","KLASSISCHE STEUERUNG","CONTROLES CLÁSICOS","COMANDI CLASSICI","クラシックコントロール","КЛАССИЧЕСКОЕ УПРАВЛЕНИЕ","클래식","经典操作","CONTROLE CLÁSSICO"},
	{"CTRL2_SETTINGS","SCREEN TAP","COMMANDES TACTILES","DIREKT BERÜHREN","PANTALLA TÁCTIL","TATTILI","スクリーンタップ","НАЖАТИЕ НА ЭКРАН","화면 터치","点击屏幕","TOQUE NA TELA"},
	{"CTRL3_SETTINGS","VIRTUAL STICKS ","STICKS VIRTUELS","STEUERELEMENTE","JOYSTICKS VIRTUALES","PAD VIRTUALI","バーチャルスティック","ВИРТУАЛЬНЫЕ ДЖОЙСТИКИ","가상 스틱","虚拟摇杆","JOYSTICK VIRTUAL"},
	{"NUM_MONEY","CREDITS GAINED:","CRÉDITS REMPORTÉS :","CREDITS ERHALTEN:","CRÉDITOS CONSEGUIDOS:","CREDITI GUADAGNATI:","獲得クレジット：","ЗАРАБОТАНО ДЕНЕГ:","획득한 크레딧:","获得点券：","CRÉDITOS ADQUIRIDOS:"},
	{"ACCURACY","ACCURACY:","PRÉCISION :","PRÄZISION:","PUNTERÍA:","PRECISIONE:","命中率：","ТОЧНОСТЬ:","명중률:","命中率：","PRECISÃO:"},
	{"NUM_DOCS","DOCUMENTS FOUND:","DOCUMENTS TROUVÉS :","DOKUMENTE GEFUNDEN:","DOC. ENCONTRADOS:","DOCUMENTI TROVATI:","発見した文書：","НАЙДЕНО ДОКУМЕНТОВ:","발견한 문서:","找到文件：","DOCUMENTOS ENCONTRADOS:"},
	{"LEVEL_DIFFICULTY","DIFFICULTY:","DIFFICULTÉ :","NIVEAU:","DIFICULTAD:","DIFFICOLTÀ:","難易度：","СЛОЖНОСТЬ:","난이도:","难度：","DIFICULDADE:"},
	{"LEVEL_TIME","YOUR TIME:","TEMPS :","ZEIT:","TU TIEMPO:","TEMPO:","クリアタイム：","ВАШЕ ВРЕМЯ:","현재 기록:","本次用时：","SEU TEMPO:"},
	{"BEST_TIME","BEST TIME:","MEILLEUR TEMPS :","BESTZEIT:","MEJOR TIEMPO:","MIGLIOR TEMPO:","ベストタイム：","ЛУЧШЕЕ ВРЕМЯ:","최고 기록:","最短用时：","MELHOR TEMPO:"},
	{"COMPLETED","COMPLETED","TERMINÉ","BEENDET","COMPLETADA","COMPLETATA","COMPLETED","ЗАВЕРШЕНО","완료","完成","CONCLUIU"},
	{"CONFIRM_QUIT","ARE YOU SURE THAT YOU WANT TO QUIT?","QUITTER ?","WILLST DU WIRKLICH DAS SPIEL BEENDEN?","¿SEGURO QUE QUIERES SALIR?","VUOI DAVVERO USCIRE?","終了します\nよろしいですか？","ВЫ ТОЧНО ХОТИТЕ ВЫЙТИ?","종료하시겠습니까?","你确定想要退出吗？","TEM CERTEZA DE QUE DESEJA SAIR?"},
	{"CONFIRM_MAINMENU","ARE YOU SURE THAT YOU WANT TO RETURN TO THE MAIN MENU?","RETOURNER AU MENU PRINCIPAL ?","WILLST DU WIRKLICH ZURÜCK ZUM HAUPTMENÜ?","¿SEGURO QUE QUIERES VOLVER AL MENÚ PRINCIPAL?","VUOI DAVVERO TORNARE AL MENU PRINCIPALE?","メインメニューに戻ります\nよろしいですか？","ВЫ ТОЧНО ХОТИТЕ ВЕРНУТЬСЯ В ГЛАВНОЕ МЕНЮ?","주 메뉴로 돌아가시겠습니까?","你确定想要返回主菜单吗？","TEM CERTEZA DE QUE DESEJA VOLTAR AO MENU PRINCIPAL?"},
	{"CONFIRM_EXITMATCH","ARE YOU SURE THAT YOU WANT TO LEAVE THIS MATCH?","ES-TU SÛR DE VOULOIR QUITTER CETTE PARTIE ?","BIST DU SICHER, DASS DU DAS SPIEL VERLASSEN MÖCHTEST?","¿SEGURO QUE QUIERES SALIR DE LA PARTIDA?","VUOI DAVVERO LASCIARE QUESTA PARTITA?","退出します\nよろしいですか？","ПОКИНУТЬ МАТЧ?","이 매치에서 나가시겠습니까?","你确定要离开比赛吗？","VOCÊ TEM CERTEZA QUE DESEJA SAIR DA PARTIDA?"},
	{"CONFIRM_RESTART","ARE YOU SURE THAT YOU WANT TO RESTART THIS MISSION?","RECOMMENCER CETTE MISSION ?","WILLST DU DIESE MISSION WIRKLICH NEU STARTEN?","¿SEGURO QUE QUIERES REINICIAR ESTA MISIÓN?","VUOI DAVVERO RICOMINCIARE LA MISSIONE?","ミッションをリスタートします\nよろしいですか？","ВЫ ТОЧНО ХОТИТЕ НАЧАТЬ ЗАДАНИЕ ЗАНОВО?","이 미션을 다시 시작하시겠습니까?","你确定想要重新开始本关吗？","TEM CERTEZA DE QUE DESEJA REINICIAR A MISSÃO?"},
	{"CONFIRM_NEWGAME","ARE YOU SURE THAT YOU WANT TO START A NEW GAME?","COMMENCER UNE NOUVELLE PARTIE ?","WILLST DU WIRKLICH EIN NEUES SPIEL STARTEN?","¿SEGURO QUE QUIERES EMPEZAR UNA NUEVA PARTIDA?","VUOI DAVVERO INIZIARE UNA NUOVA PARTITA?","新しくゲームを開始します\n以前のプレイデータは\n失われます","ВЫ ТОЧНО ХОТИТЕ НАЧАТЬ ИГРУ ЗАНОВО?","게임을 새로 시작하시겠습니까?","你确定想要开始一个新的游戏吗？","TEM CERTEZA DE QUE DESEJA INICIAR UMA NOVA PARTIDA?"},
	{"CONFIRM_CHECKPOINT","ARE YOU SURE THAT YOU WANT TO RELOAD THE LAST CHECKPOINT?","REPRENDRE DU DERNIER CHECKPOINT ?","WILLST DU WIRKLICH DEN LETZTEN SPEICHERPUNKT LADEN?","¿SEGURO QUE QUIERES EMPEZAR DESDE EL ÚLTIMO PUNTO DE CONTROL?","VUOI DAVVERO RIPARTIRE DALL'ULTIMO CHECKPOINT?","直前のチェックポイントに|戻ります\nよろしいですか？","ВЫ ТОЧНО ХОТИТЕ НАЧАТЬ С ПОСЛЕДНЕЙ КОНТРОЛЬНОЙ ТОЧКИ?","마지막 체크포인트를 다시 불러오시겠습니까?","你确定要从最近的存档点重新开始吗？","TEM CERTEZA DE QUE DESEJA RECARREGAR O ÚLTIMO CHECKPOINT?"},
	{"CONFIRM_YES","YES","OUI","JA","SÍ","SÌ","はい","ДА","예","是","SIM"},
	{"CONFIRM_NO","NO","NON","NEIN","NO","NO","いいえ","НЕТ","아니요","否","NÃO"},
	{"CONFIRM_REHOST","ARE YOU SURE YOU WANT TO END THIS GAME AND START ANOTHER ONE?","TERMINER CETTE PARTIE ET EN COMMENCER UNE NOUVELLE ?","WILLST DU WIRKLICH DIESES SPIEL BEENDEN UND EIN NEUES STARTEN?","¿SEGURO QUE QUIERES SALIR DE ESTA PARTIDA Y EMPEZAR UNA NUEVA?","VUOI TERMINARE QUESTA PARTITA E INIZIARNE UNA NUOVA?","この対戦を終了して|別の対戦を始めます\nよろしいですか？","ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ ЗАВЕРШИТЬ ЭТУ ИГРУ И НАЧАТЬ НОВУЮ?","이 게임을 끝내고 다른 게임을 시작하시겠습니까?","你确定想要结束此关游戏并重新开始新的游戏吗？","TEM CERTEZA DE QUE DESEJA ENCERRAR ESTA PARTIDA E INICIAR OUTRA?"},
	{"CONFIRM_BACK","BACK","RETOUR","ZURÜCK","ATRÁS","INDIETRO","戻る","BACK","뒤로","返回","VOLTAR"},
	{"CONFIRM_SUICIDE","CHOOSING THIS OPTION WILL CAUSE YOU TO DIE. ARE YOU SURE YOU WANT TO CONTINUE?","TON PERSONNAGE MOURRA SI TU CHOISIS CETTE OPTION. CONTINUER ?","WENN DU DIESE OPTION WÄHLST, STIRBST DU. WIRKLICH FORTFAHREN?","SI ELIGES ESTA OPCIÓN, MORIRÁS. ¿SEGURO QUE QUIERES CONTINUAR?","SE SCEGLI QUESTA OPZIONE, MORIRAI. VUOI DAVVERO CONTINUARE?","デスの|スコアが|+1され|再出撃と|なります\nよろしい|ですか？","ВЫБОР ЭТОЙ ФУНКЦИИ ПРИВЕДЕТ К СМЕРТИ ПЕРСОНАЖА. ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ ПРОДОЛЖИТЬ?","이 옵션을 선택하면 죽게 됩니다. 계속하시겠습니까?","选择此项意味自杀身亡。你确定想要继续？","ESTA OPÇÃO RESULTARÁ EM SUA MORTE. TEM CERTEZA DE QUE DESEJA CONTINUAR?"},
	{"CONFIRM_RESET_SAVEGAME","STARTING THIS LEVEL WILL ERASE YOUR PREVIOUS SAVED GAME. CONTINUE?","SI TU COMMENCES CE NIVEAU, TA PROGRESSION SERA EFFACÉE. CONTINUER ?","WENN DU DIESEN LEVEL STARTEST, GEHT DEIN BISHERIGER FORTSCHRITT VERLOREN. FORTFAHREN?","SI EMPIEZAS ESTE NIVEL, SE BORRARÁ TU ANTERIOR PARTIDA GUARDADA. ¿QUIERES CONTINUAR?","SE INIZIERAI QUESTO LIVELLO, PERDERAI I SALVATAGGI PRECEDENTI. CONTINUARE?","このステージを|開始すると|以前の|ステージの\n途中データが|削除されます\nよろしいですか？","ПРЕДЫДУЩИЕ СОХРАНЕНИЯ БУДУТ УДАЛЕНЫ, ЕСЛИ ВЫ НАЧНЕТЕ ЭТОТ УРОВЕНЬ. ПРОДОЛЖИТЬ?","이 레벨을 시작하면 이전에 저장된 게임이 삭제됩니다. 계속하시겠습니까?","开始本关会清除你之前的储存进度。要继续吗？","SE VOCÊ COMEÇAR ESSE NÍVEL VAI APAGAR SEU JOGO SALVO ANTERIORMENTE. DESEJA CONTINUAR?"},
	{"EASY_DIFFICULTY","EASY ","FACILE","LEICHT","BAJA","FACILE","イージー","ЛЕГКО","쉬움","简单","FÁCIL"},
	{"NORMAL_DIFFICULTY","NORMAL ","NORMAL","NORMAL","MEDIA","NORMALE","ノーマル","НОРМАЛЬНО","보통","普通","NORMAL"},
	{"HARD_DIFFICULTY","HARD ","DIFFICILE","SCHWER","ALTA","DIFFICILE","ハード","ТЯЖЕЛО","어려움","困难","DIFÍCIL"},
	{"EXTREME_DIFFICULTY","EXTREME ","EXTRÊME","EXTREM","EXTREMA","ESTREMA","エクストリーム","ЭКСТРИМ","아주 어려움","噩梦","EXTREMO"},
	{"PRESS","TOUCH ","TOUCHE","BILDSCHIRM BERÜHREN:","TOCA","TOCCA","タップして","НАЖМИТЕ","계속하려면","触摸","TOQUE"},
	{"TO_CONTINUE","TO CONTINUE ","POUR CONTINUER","WEITER","PARA CONTINUAR","PER CONTINUARE","コンティニュー","ЧТОБЫ ПРОДОЛЖИТЬ","터치하세요","以继续","PARA CONTINUAR"},
	{"BACK","BACK ","RETOUR","ZURÜCK","ATRÁS","INDIETRO","戻る","НАЗАД","뒤로","返回","VOLTAR"},
	{"LOADING","LOADING","CHARGEMENT","LÄDT","CARGANDO","CARICAMENTO","LOADING","ЗАГРУЗКА","불러오는 중","载入中","CARREGANDO"},
	{"MAX","MAX","MAX.","MAX.","MÁX.","MAX","MAX","МАКС","최대","最高","MÁX."},
	{"HEALTH","Health","Santé","Gesundheit","Salud","Energia","Health","ЗДОРОВЬЕ","체력","生命值","Saúde"},
	{"YOU","YOU","TOI","DU","TÚ","TU","あなた","Вы","나","你","VOCÊ"},
	{"SUDDEN_DEATH","SUDDEN DEATH!","MORT SUBITE !","PLÖTZLICHER TOD!","¡MUERTE SÚBITA!","MORTE IMPROVVISA","サドンデス","НЕОЖИДАННАЯ СМЕРТЬ!!!","서든데스!","突然死亡！","MORTE SÚBITA!"},
	{"TROPH_TITLE","To Be Continued?","À suivre ?","Fortsetzung folgt?","¿Continuará?","La storia continua...","プロローグ","Продолжение следует?","전투의 서막","继续？","Continua...?"}
};

#endif